version: "3.9"

networks:
  internalNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: "172.28.0.0/16"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      dbIP: ${dbIP}
      port: ${port}
    networks:
      - internalNetwork
    depends_on:
      - database
    command: /bin/sh -c "until nc -z database 5432; do echo 'Waiting for DB...'; sleep 2; done; npm start"

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      internalNetwork:
        ipv4_address: 172.28.0.10
    expose:
      - "5432"
